CREATE TABLE LOG3(
actionType VARCHAR2(20),
userName VARCHAR2(100),
dateLog DATE,
rowsNum number);

--процедура
CREATE OR REPLACE PROCEDURE IN_OUT_WRITER (VOPER IN VARCHAR2) IS
PRAGMA AUTONOMOUS_TRANSACTION;
rowsN number;
BEGIN
    SELECT COUNT(*) into rowsN from supervisor;
	INSERT INTO LOG3 VALUES (VOPER,USER,SYSDATE,rowsN);
	COMMIT;
END;
/

--2 СИСТЕМНЫХ ТРИГГЕРА

--на вход
CREATE OR REPLACE TRIGGER IN_AUD AFTER LOGON ON schema
BEGIN
	IN_OUT_WRITER(ORA_SYSEVENT);
END;
/

--на выход
CREATE OR REPLACE TRIGGER OUT_AUD BEFORE LOGOFF ON schema
BEGIN
	IN_OUT_WRITER(ORA_SYSEVENT);
END;
/

select * from LOG3;
